name: Pull Request (CI)
on: 
  push:
    branches: 
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
        echo "I'm a modified push job".
        sleep 30s
  skipped-job:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - run: echo "Will I show up?"
