name: Release
on:
  create:
    branches:
      - '^[Rr]elease\/v[0-9]+\.*[0-9]*\.*[0-9]*$'
jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Generate Version Output
        run: |
          echo ${{ github.ref }}
          echo ${{ github.ref }} | sed 's?refs/heads/Release/??'
          echo ::set-output name=semver::$(echo ${{ github.ref }} | sed 's?refs/heads/Release/??')
          echo ${{ steps.vars.outputs.semver }}
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.semver }}
          release_name: Release ${{ steps.vars.outputs.semver }}
          body: |
            Sample release notes for now.
          draft: false
          prerelease: false