name: On Release PreReleased
on:
  release: 
    types: [prereleased,published]
jobs:
  test:
    name: PreReleased test
    runs-on: ubuntu-latest
    steps:
      - name: Echo stuff
        run: |
          echo $GITHUB_REF
          echo $GITHUB_RUN_ID
          echo $GITHUB_SHA