
# name: Release
# on:
#   create:
#     branches:
#       - '^[Rr]elease\/v[0-9]+\.*[0-9]*\.*[0-9]*$'
# jobs:
#   create-release:
#     name: Create Release
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout Code
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 0
#       - name: Generate Version Output
#         id: generate_version
#         run: |
#           echo "::set-output name=semver::$(echo ${{ github.ref }} | sed 's?refs/heads/Release/??')"
#       - name: Generate Release Notes
#         run: |
#           readarray -t -d '-' tagDescriptionArray<<< "$(git describe --tags --long)"
#           echo "${tagDescriptionArray[@]}"
          
#       - name: Create Release
#         uses: actions/create-release@v1
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         with:
#           tag_name: ${{ steps.generate_version.outputs.semver }}
#           release_name: Release ${{ steps.generate_version.outputs.semver }}
#           body: |
#             Sample release notes for now.
#           draft: false
#           prerelease: false